swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /resumes:
        get:
            tags:
                - resume
            summary: list resume
            description: List all stored resumes
            operationId: resume#list
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ResumeStoredResumeResponseCollection'
            schemes:
                - http
        post:
            tags:
                - resume
            summary: add resume
            description: Add n number of resumes and return their IDs. This is a multipart request and each part has field name 'resume' and contains the encoded resume to be added.
            operationId: resume#add
            consumes:
                - multipart/form-data
            parameters:
                - name: array
                  in: formData
                  required: true
                  schema:
                    type: array
                    items:
                        $ref: '#/definitions/Resume'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: integer
                            example: 7211099879937814092
                            format: int64
            schemes:
                - http
definitions:
    Education:
        title: Education
        type: object
        properties:
            institution:
                type: string
                description: Name of the institution
                example: Veniam quis sit vel.
            major:
                type: string
                description: Major name
                example: Nihil rem ut saepe.
        example:
            institution: Quae sunt aut qui corporis molestiae.
            major: Ducimus quo hic aut cumque dicta autem.
        required:
            - institution
            - major
    Experience:
        title: Experience
        type: object
        properties:
            company:
                type: string
                description: Name of the company
                example: Praesentium facilis qui.
            duration:
                type: integer
                description: Duration (in years) in the company
                example: 6989244634499720859
                format: int64
            role:
                type: string
                description: Name of the role in the company
                example: Voluptates libero consectetur in.
        example:
            company: Nesciunt harum.
            duration: 2478818273192673290
            role: Qui reprehenderit aut.
        required:
            - company
            - role
            - duration
    Resume:
        title: Resume
        type: object
        properties:
            education:
                type: array
                items:
                    $ref: '#/definitions/Education'
                description: Education section in the resume
                example:
                    - institution: Nihil voluptate dolorem ut ipsam fuga.
                      major: Ex sequi.
                    - institution: Nihil voluptate dolorem ut ipsam fuga.
                      major: Ex sequi.
            experience:
                type: array
                items:
                    $ref: '#/definitions/Experience'
                description: Experience section in the resume
                example:
                    - company: Saepe similique libero sunt.
                      duration: 4538661945567210561
                      role: Cum maiores quo at ducimus sit.
                    - company: Saepe similique libero sunt.
                      duration: 4538661945567210561
                      role: Cum maiores quo at ducimus sit.
                    - company: Saepe similique libero sunt.
                      duration: 4538661945567210561
                      role: Cum maiores quo at ducimus sit.
            name:
                type: string
                description: Name in the resume
                example: Molestiae atque reprehenderit molestiae.
        example:
            education:
                - institution: Nihil voluptate dolorem ut ipsam fuga.
                  major: Ex sequi.
                - institution: Nihil voluptate dolorem ut ipsam fuga.
                  major: Ex sequi.
            experience:
                - company: Saepe similique libero sunt.
                  duration: 4538661945567210561
                  role: Cum maiores quo at ducimus sit.
                - company: Saepe similique libero sunt.
                  duration: 4538661945567210561
                  role: Cum maiores quo at ducimus sit.
                - company: Saepe similique libero sunt.
                  duration: 4538661945567210561
                  role: Cum maiores quo at ducimus sit.
            name: Natus aliquam ratione.
        required:
            - name
    ResumeStoredResumeResponseCollection:
        title: 'Mediatype identifier: application/vnd.goa.resume; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/StoredResumeResponse'
        description: ListResponseBody is the result type for an array of StoredResumeResponse (default view)
        example:
            - created_at: Tempore quidem animi nihil.
              education:
                - institution: Mollitia dolores sequi sed veritatis totam omnis.
                  major: Repellendus et et aut sint.
                - institution: Mollitia dolores sequi sed veritatis totam omnis.
                  major: Repellendus et et aut sint.
              experience:
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
              id: 47036700361575944
              name: Assumenda sed.
            - created_at: Tempore quidem animi nihil.
              education:
                - institution: Mollitia dolores sequi sed veritatis totam omnis.
                  major: Repellendus et et aut sint.
                - institution: Mollitia dolores sequi sed veritatis totam omnis.
                  major: Repellendus et et aut sint.
              experience:
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
              id: 47036700361575944
              name: Assumenda sed.
            - created_at: Tempore quidem animi nihil.
              education:
                - institution: Mollitia dolores sequi sed veritatis totam omnis.
                  major: Repellendus et et aut sint.
                - institution: Mollitia dolores sequi sed veritatis totam omnis.
                  major: Repellendus et et aut sint.
              experience:
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
              id: 47036700361575944
              name: Assumenda sed.
    StoredResumeResponse:
        title: 'Mediatype identifier: application/vnd.goa.resume; view=default'
        type: object
        properties:
            created_at:
                type: string
                description: Time when resume was created
                example: Voluptas fuga.
            education:
                type: array
                items:
                    $ref: '#/definitions/Education'
                description: Education section in the resume
                example:
                    - institution: Mollitia dolores sequi sed veritatis totam omnis.
                      major: Repellendus et et aut sint.
                    - institution: Mollitia dolores sequi sed veritatis totam omnis.
                      major: Repellendus et et aut sint.
                    - institution: Mollitia dolores sequi sed veritatis totam omnis.
                      major: Repellendus et et aut sint.
                    - institution: Mollitia dolores sequi sed veritatis totam omnis.
                      major: Repellendus et et aut sint.
            experience:
                type: array
                items:
                    $ref: '#/definitions/Experience'
                description: Experience section in the resume
                example:
                    - company: Aut rem.
                      duration: 5176619058752078184
                      role: Consequuntur quam est commodi cumque eaque quisquam.
                    - company: Aut rem.
                      duration: 5176619058752078184
                      role: Consequuntur quam est commodi cumque eaque quisquam.
            id:
                type: integer
                description: ID of the resume
                example: 1079998222644937168
                format: int64
            name:
                type: string
                description: Name in the resume
                example: Consequuntur pariatur ad accusantium.
        description: StoredResumeResponse result type (default view)
        example:
            created_at: Non aut quas corporis.
            education:
                - institution: Mollitia dolores sequi sed veritatis totam omnis.
                  major: Repellendus et et aut sint.
                - institution: Mollitia dolores sequi sed veritatis totam omnis.
                  major: Repellendus et et aut sint.
                - institution: Mollitia dolores sequi sed veritatis totam omnis.
                  major: Repellendus et et aut sint.
            experience:
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
                - company: Aut rem.
                  duration: 5176619058752078184
                  role: Consequuntur quam est commodi cumque eaque quisquam.
            id: 2720030110273853670
            name: Aut molestiae recusandae.
        required:
            - id
            - name
            - experience
            - education
            - created_at
